apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-backend
  namespace: argocd
  annotations: {}
  labels:
    app.kubernetes.io/name: blog-backend
spec:
  project: default
  source:
    repoURL: github.com/Bready1222/blog-backend.git
    path: k8s
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true       # 自动清理 Git 中删除的资源
      selfHeal: true    # 自动修复被手动修改的资源
      allowEmpty: false # 建议设为 false，防止误删所有资源
    syncOptions:
      - CreateNamespace=true
      - Validate=false  # 跳过部分严格验证，减少同步报错