apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog-backend-deploy.yaml
images:
  - name: 192.168.23.128/blog-backend/blog-backend
    newTag: "1.0.0"  # 初始值，Updater会自动替换为最新的1.0.x版本
